Update post.install

diff --git a/post.install b/post.install
--- a/post.install
+++ b/post.install
@@ -1,12 +1,9 @@
 #!/bin/bash
+# autoexit on error
+set -e 
 # Repos and ppas
-sudo add-apt-repository -y "deb http://dl.google.com/linux/chrome/deb/ stable main"
-sudo add-apt-repository -y "deb http://dl.google.com/linux/talkplugin/deb/ stable main"
-sudo apt-add-repository -y ppa:mc3man/trusty-media
 sudo add-apt-repository -y ppa:danielrichter2007/grub-customizer
 sudo add-apt-repository -y ppa:xorg-edgers/ppa #NVIDIA drivers
-sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
-wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
 
 # Update and upgrage
 sudo apt-get -y --force-yes update
@@ -16,22 +13,17 @@ sudo apt-get -y --force-yes upgrade
 sudo apt-get -y install konsole mc git vim-gtk gparted openssh-server python-dev \
     silversearcher-ag thunderbird grub-customizer kdiff3 keepass2 \
     gnome-calculator audacity audacious build-essential \
-    cmake conky dconf-tools dos2unix exfat-utils exfat-fuse google-chrome-stable \
+    cmake conky dconf-tools dos2unix exfat-utils exfat-fuse \
     transmission goldendict gufw leafpad dkms linux-headers-generic mono-complete fsharp
 
 #Install File Compression Libs
 sudo apt-get -y install unace rar unrar zip unzip lzip lunzip xz-utils p7zip-full p7zip-rar sharutils uudeview mpack arj cabextract 
 
 #Codecs
-sudo apt-get -y install ffmpeg gstreamer0.10-plugins-ugly libavcodec-extra libvdpau-va-gl1 libmad0 mpg321 gstreamer1.0-libav
-
-#Remove some Switchboard Plug's
-sudo rm -rf /usr/lib/plugs/GnomeCC/gnomecc-bluetooth.plug
-sudo rm -rf /usr/lib/plugs/GnomeCC/gnomecc-wacom.plug
+sudo apt-get -y install ffmpeg libavcodec-extra libvdpau-va-gl1 libmad0 mpg321 gstreamer1.0-libav
 
 #Clean-up System
-sudo apt-get remove nvidia*
-sudo apt-get -y purge midori-granite noise bluez geary modemmanager 
+sudo apt-get -y remove nvidia*
 sudo apt-get -y autoremove
 sudo apt-get -y autoclean
 
@@ -40,77 +32,80 @@ sudo apt-get -y autoclean
 echo "Installing Telegram"
 sleep 2
 cd /tmp
-wget -o telegram https://tdesktop.com/linux
-tar -xJvf linux
+sudo wget -O telegram https://tdesktop.com/linux
+sudo tar -xJvf telegram
 sudo mv Telegram /opt/telegram
 sudo ln -sf /opt/telegram /usr/bin/telegram
 
 echo "Installing Screenfetch"
 sleep 2
-sudo wget -O /usr/share/bin/screenfetch 'https://raw.github.com/KittyKatt/screenFetch/master/screenfetch-dev'
-sudo chmod +x /usr/share/bin/screenfetch
-
-echo "Installing Dropbox"
-sleep 2
-yes | git clone https://github.com/zant95/elementary-dropbox
-sudo bash ./elementary-dropbox/install.sh -y
+cd /usr/local/bin
+sudo wget -O screenfetch 'https://raw.github.com/KittyKatt/screenFetch/master/screenfetch-dev'
+sudo chmod +x screenfetch
 
 echo "Installing Teamviewer"
 sleep 2
+cd /tmp
 wget http://download.teamviewer.com/download/teamviewer_i386.deb
-sudo dpkg -i teamviewer_i386.deb
-sudo apt-get -fy install
+sudo dpkg -i teamviewer_i386.deb || sudo apt-get -fy install
 
 echo "Installing dmitr's dotfiles"
 sleep 2
+cd /tmp
 yes | git clone https://github.com/dmitrymarchuk/dotfiles.git
-shopt -s dotglob
-/bin/cp -ar ./dotfiles/* ~
-sudo cp -ar ./dotfiles/usr/share/fonts/* /usr/share/fonts
+sudo cp -r ./dotfiles/home/. ~
+sudo cp -r ./dotfiles/usr/. /usr
+yes | sudo git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
 
-echo "Settings up folders"
+echo "Setting up folders"
 sleep 2
 rm -rf ~/Public
 rm -rf ~/Templates
 rm -rf ~/Videos
 mkdir ~/Dev
 
-echo "Settings up settings"
+echo "Setting up settings"
 sleep 2
-gsettings set com.canonical.indicator.messages applications "['thunderbird.desktop']"
-gsettings set com.canonical.indicator.sound interested-media-players "['vlc.desktop', 'noise.desktop']"
-gsettings set org.gnome.calculator button-mode 'programming'
-gsettings set org.gnome.desktop.default-applications.terminal exec 'konsole'
-gsettings set org.gnome.desktop.input-sources per-window true
-gsettings set org.gnome.desktop.default-applications.terminal exec-arg ''
-gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'ru+typewriter')]"
-gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
-gsettings set org.gnome.desktop.interface document-font-name 'Droid Sans 10'
-gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 10'
-gsettings set org.gnome.desktop.interface scaling-factor uint32 1
-gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/DecorationLayout': <':minimize,maximize,close'>}"
-gsettings set org.pantheon.desktop.gala.appearance button-layout ':minimize,maximize,close'
-gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'
-gsettings set org.gnome.settings-daemon.peripherals.mouse motion-acceleration 1.0
-gsettings set org.gnome.settings-daemon.peripherals.mouse motion-threshold 10
-gsettings set org.gnome.settings-daemon.peripherals.touchpad touchpad-enabled false
-gsettings set org.gnome.settings-daemon.plugins.media-keys calculator '<Primary>F12'
-gsettings set org.gnome.settings-daemon.plugins.media-keys home '<Super>e'
-gsettings set org.gnome.settings-daemon.plugins.media-keys terminal '<Primary>grave'
-gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down '<Alt><Super>Down'
-gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up '<Alt><Super>Up'
-gsettings set org.gnome.settings-daemon.plugins.power button-power 'shutdown'
-gsettings set org.gnome.settings-daemon.plugins.xsettings hinting 'full'
-gsettings set org.pantheon.desktop.gala.keybindings switch-input-source "['<Primary>space']"
-gsettings set org.pantheon.desktop.gala.notifications apps "['NetworkManager:show,on', 'Power:show,on', ':show,on', 'terminal:show,on', 'dropbox:show,on', 'konsole:show,on', 'transmission:show,on', 'vlc:show,on']"
-gsettings set org.pantheon.desktop.slingshot screen-resolution '1920x1080'
-gsettings set org.pantheon.files.preferences maximized false
-gsettings set org.pantheon.files.preferences sidebar-width 191
-gsettings set org.pantheon.files.preferences tab-info-list "[(uint32 0, 'file%3A%2F%2F%2Fmedia%2Fpassport', '')]"
-gsettings set org.pantheon.noise.saved-state more-width 1
-gsettings set org.pantheon.noise.settings music-folder '/home/dmitr/Music'
+#gsettings set com.canonical.indicator.messages applications "['thunderbird.desktop']"
+#gsettings set com.canonical.indicator.sound interested-media-players "['vlc.desktop', 'noise.desktop']"
+#gsettings set org.gnome.calculator button-mode 'programming'
+#gsettings set org.gnome.desktop.default-applications.terminal exec 'konsole'
+#gsettings set org.gnome.desktop.input-sources per-window true
+#gsettings set org.gnome.desktop.default-applications.terminal exec-arg ''
+#gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'ru+typewriter')]"
+#gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
+#gsettings set org.gnome.desktop.interface document-font-name 'Droid Sans 10'
+#gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 10'
+#gsettings set org.gnome.desktop.interface scaling-factor uint32 1
+#gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/DecorationLayout': <':minimize,maximize,close'>}"
+#gsettings set org.pantheon.desktop.gala.appearance button-layout ':minimize,maximize,close'
+#gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'
+#gsettings set org.gnome.settings-daemon.peripherals.mouse motion-acceleration 1.0
+#gsettings set org.gnome.settings-daemon.peripherals.mouse motion-threshold 10
+#gsettings set org.gnome.settings-daemon.peripherals.touchpad touchpad-enabled false
+#gsettings set org.gnome.settings-daemon.plugins.media-keys calculator '<Primary>F12'
+#gsettings set org.gnome.settings-daemon.plugins.media-keys home '<Super>e'
+#gsettings set org.gnome.settings-daemon.plugins.media-keys terminal '<Primary>grave'
+#gsettings set org.gnome.settings-daemon.plugins.media-keys volume-down '<Alt><Super>Down'
+#gsettings set org.gnome.settings-daemon.plugins.media-keys volume-up '<Alt><Super>Up'
+#gsettings set org.gnome.settings-daemon.plugins.power button-power 'shutdown'
+#gsettings set org.gnome.settings-daemon.plugins.xsettings hinting 'full'
+#gsettings set org.pantheon.desktop.gala.keybindings switch-input-source "['<Primary>space']"
+#gsettings set org.pantheon.desktop.gala.notifications apps "['NetworkManager:show,on', 'Power:show,on', ':show,on', 'terminal:show,on', 'dropbox:show,on', 'konsole:show,on', 'transmission:show,on', 'vlc:show,on']"
+#gsettings set org.pantheon.desktop.slingshot screen-resolution '1920x1080'
+#gsettings set org.pantheon.files.preferences maximized false
+#gsettings set org.pantheon.files.preferences sidebar-width 191
+#gsettings set org.pantheon.files.preferences tab-info-list "[(uint32 0, 'file%3A%2F%2F%2Fmedia%2Fpassport', '')]"
+#gsettings set org.pantheon.noise.saved-state more-width 1
+#gsettings set org.pantheon.noise.settings music-folder '/home/dmitr/Music'
 
 echo "Final steps. Require user action"
+echo "Installing Dropbox"
+sleep 2
+sudo apt-get install dropbox python-gpgme
+dropbox start -i
+
+echo "Ubuntu restricted extras"
 sleep 2
 sudo apt-get install -y ubuntu-restricted-extras
 sudo apt-get dist-upgrade
@@ -118,38 +113,10 @@ sudo apt-get dist-upgrade
 echo "Installing NVIDIA driver"
 sleep 2
 #Nvidia
-sudo echo "blacklist nouveau
-blacklist lbm-nouveau
-options nouveau modeset=0
-alias nouveau off
-alias lbm-nouveau off" >> /etc/modprobe.d/blacklist-nouveau.conf
+echo "blacklist nouveau\nblacklist lbm-nouveau\noptions nouveau modeset=0\nalias nouveau off\nalias lbm-nouveau off" | sudo tee -a /etc/modprobe.d/blacklist-nouveau.conf
 echo options nouveau modeset=0 | sudo tee -a /etc/modprobe.d/nouveau-kms.conf
 sudo update-initramfs -u
-sudo /etc/init.d/lightdm stop
+sudo /etc/init.d/*dm stop
 sudo apt-get install nvidia-current
 
-clear
-echo ""
-echo "===================="
-echo " TIME FOR REBOOT! "
-echo "===================="
-echo ""
-sleep 5
 reboot
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
